=== MovieLabs/OMC/JSON-Schema/omc/MediaCreationContext/Character.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "",
	"type": "object",
	"title": "Character",
	"description": "A sentient entity (usually a person but not always) in the script whose specific identity is consequential to the narrative. A Character is generally identified by a specific name.",
	"required": [
		"identifier",
		"entityType"
	],
	"properties": {
		"entityInfo": {
			"title": "Entity Information",
			"$ref": "../Model/definitions.json#/properties/entityInfo"
		},
		"entityType": {
			"type": "string",
			"title": "Entity Type",
			"const": "Character"
		},
		"identifier": {
			"title": "identifier",
			"$ref": "../Utility/identifier.json#"
		},
		"name": {
			"type": [
				"string",
				"null"
			],
			"title": "Asset name",
			"description": "The primary name used for the character"
		},
		"description": {
			"title": "Character Description",
			"description": "A brief description of the character",
			"type": [
				"string",
				"null"
			]
		},
		"characterName": {
			"title": "Character Name",
			"description": "Detailed name, may include titles, alternate names, prefixes and suffixes ",
			"$ref": "../Utility/completeName.json#"
		},
		"profile": {
			"type": "object",
			"title": "Profile",
			"properties": {
				"physicalCharacteristics": {
					"type": "object",
					"title": "Physical Characteristics",
					"description": "Allows for the the description of certain physical characteristics on a character, things that might be useful to an art department, wardrobe or casting for example.",
					"properties": {
						"species": {
							"type": "string",
							"title": "Species",
							"description": "A species to which this character belongs",
							"examples": [
								"Human",
								"Borg",
								"Goblin",
								"Frog"
							]
						},
						"hairColor": {
							"type": "string",
							"title": "Hair Color",
							"description": "The hair color of the character",
							"examples": [
								"Brown",
								"Pink",
								"Blonde",
								""
							]
						},
						"hairLength": {
							"type": "string",
							"title": "Hair Length",
							"description": "The length of hair of the character"
						},
						"eyeColor": {
							"type": "string",
							"title": "Eye Color",
							"description": "The color of the characters eyes"
						},
						"height": {
							"title": "height",
							"$ref": "../Utility/unitOfMeasurement.json#/properties/linearDistance"
						},
						"weight": {
							"title": "weight",
							"$ref": "../Utility/unitOfMeasurement.json#/properties/weight"
						}
					},
					"additionalProperties": false
				},
				"gender": {
					"$ref": "../Utility/gender.json"
				},
				"background": {
					"type": "object",
					"title": "background",
					"additionalProperties": true
				}
			},
			"additionalProperties": false
		},
		"customData": {
			"title": "Custom Data",
			"$ref": "../Model/definitions.json#/properties/customData"
		},
		"Context": {
			"title": "Character Context",
			"$ref": "./Context.json"
		}
	}
}

=== MovieLabs/OMC/Examples/test.json
{
  "entityType": "Character",
  "identifier": [
    {
      "identifierValue": "1234",
      "identifierScope": "Movielabs"
    }
  ],
  "name": "Sven",
  "description": "An unassuming satellite repair man",
  "Context": {
    "entityType": "Context",
    "identifier": [
      {
        "identifierValue": "5678",
        "identifierScope": "Movielabs"
      }
    ],
    "isPortrayedBy": {
      "Participant": {
        "entityType": "Participant",
        "identifier": [
          {
            "identifierValue": "5678",
            "identifierScope": "Movielabs"
          }
        ],
        "name": "J. Warren Trezevant",
        "description": "Stunt actor doing mo-cap for Sven",
        "structuralCharacteristics": {
          "structuralType": "person"
        },
        "functionalCharacteristics": {
          "functionalType": "stunts"
        },
        "Context": {
          "entityType": "Context",
          "identifier": [
            {
              "identifierValue": "9786",
              "identifierScope": "Movielabs"
            }
          ],
          "portrays": {
            "entityType": "Character",
            "identifier": [
              {
                "identifierValue": "1234",
                "identifierScope": "Movielabs"
              }
            ]
          }
        }
      }
    }
  }
}
