=== MovieLabs/OMC/JSON-Schema/omc/MediaCreationContext/NarrativeWardrobe.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Narrative Wardrobe",
	"description": "The clothing for a Character in the narrative.",
	"type": "object",
	"required": [
		"entityType",
		"identifier"
	],
	"properties": {
		"entityInfo": {
			"title": "Entity Information",
			"$ref": "../Model/definitions.json#/properties/entityInfo"
		},
		"entityType": {
			"type": "string",
			"title": "Entity Type",
			"const": "NarrativeWardrobe"
		},
		"identifier": {
			"$ref": "../Utility/identifier.json"
		},
		"name": {
			"title": "Narrative Wardrobe Name",
			"description": "A human readable name for the narrative wardrobe",
			"type": [
				"string",
				"null"
			]
		},
		"description": {
			"title": "Narrative Wardrobe Description",
			"description": "A brief description of the narrative wardrobe",
			"type": [
				"string",
				"null"
			]
		},
		"customData": {
			"title": "Custom Data",
			"$ref": "../Model/definitions.json#/properties/customData"
		},
		"Context": {
			"title": "Narrative Wardrobe Context",
			"description": "Informs scope within the construction process of a Creative Work by describing related entities",
			"type": "object",
			"required": [
				"entityType",
				"identifier"
			],
			"properties": {
				"entityInfo": {
					"title": "Entity Information",
					"$ref": "../Model/definitions.json#/properties/entityInfo"
				},
				"entityType": {
					"type": "string",
					"title": "Entity Type",
					"const": "Context"
				},
				"identifier": {
					"$ref": "../Utility/identifier.json"
				},
				"isUsedIn": {
					"title": "isUsedIn",
					"type": "object",
					"properties": {
						"NarrativeScene": {
							"type": "array",
							"items": {
								"$ref": "../MediaCreationContext/NarrativeScene.json"
							}
						}
					}
				},
				"isWardrobeFor": {
					"title": "isWardrobeFor",
					"type": "object",
					"properties": {
						"Character": {
							"type": "array",
							"items": {
								"$ref": "../MediaCreationContext/Character.json"
							}
						}
					}
				}
			},
			"additionalProperties": true
		}
	},
	"additionalProperties": true
}

=== MovieLabs/OMC/Examples/allWardrobe.json
[
  {
    "entityType": "NarrativeWardrobe",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "wrd/Ia7-FdhY1yBFyqG_2nYW8"
      }
    ],
    "name": "Spacesuit",
    "description": "RD-12 Envrionmental Protection Suit",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/wWz2OqsKDO7bTLZm9TdTJ"
        }
      ],
      "isWardrobeFor": {
        "Character": [
          {
            "entityType": "Character",
            "identifier": [
              {
                "identifierScope": "labkoat",
                "identifierValue": "chr/HNvHjXqJY9wv1IwjG-Hf1"
              }
            ]
          }
        ]
      }
    }
  },
  {
    "entityType": "NarrativeWardrobe",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "wrd/Hex65mL3RTBcLiGmAVh8d"
      }
    ],
    "name": "Killamari exo-skeleton",
    "description": "The life long container of the dreaded Killamari.",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/CTkF7d29sRbVLTfYB6RhU"
        }
      ],
      "isWardrobeFor": {
        "Character": [
          {
            "entityType": "Character",
            "identifier": [
              {
                "identifierScope": "labkoat",
                "identifierValue": "chr/LC4nrtxXR3CVPDUr8DAOJ"
              }
            ]
          }
        ]
      }
    }
  }
]
