=== MovieLabs/OMC/JSON-Schema/omc/MediaCreationContext/ProductionLocation.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "",
	"title": "ProductionLocation",
	"description": "A real place that is used to depict the Narrative Location or used for creating the production.",
	"type": "object",
	"required": [
		"entityType",
		"identifier"
	],
	"properties": {
		"entityInfo": {
			"title": "Entity Information",
			"$ref": "../Model/definitions.json#/properties/entityInfo"
		},
		"entityType": {
			"title": "Entity Type",
			"type": "string",
			"const": "ProductionLocation"
		},
		"identifier": {
			"$ref": "../Utility/identifier.json"
		},
		"Location": {
			"$ref": "../Utility/Location.json"
		},
		"name": {
			"title": "Production Location Name",
			"description": "A human readable name for the location",
			"type": [
				"string",
				"null"
			]
		},
		"description": {
			"title": "Production Location Description",
			"description": "A brief description of the production location",
			"type": [
				"string",
				"null"
			]
		},
		"locationType": {
			"description": "Describes whether this is production location or more specifically a shooting location",
			"enum": ["production", "shooting"],
			"default": "production"
		},
		"customData": {
			"title": "Custom Data",
			"$ref": "../Model/definitions.json#/properties/customData"
		},
		"Context": {
			"title": "Production Location Context",
			"$ref": "./Context.json"
		}
	}
}

=== MovieLabs/OMC/Examples/allProductionLocations.json
[
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/DBMKDFZ5G7PBwtgK2PXBG"
      }
    ],
    "name": "Game On ",
    "description": "Motion Capture Stage",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/CJXwmiWy3cXV802h-5fWI"
        }
      ],
      "address": {
        "street": "405 Av. Ogilvy B",
        "locality": "Montr√©al",
        "region": null,
        "postalCode": "QC H3N 1M3",
        "country": "CA"
      },
      "coordinates": {
        "latitude": 45.53072,
        "longitude": -73.62522
      }
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/06CvKXkLgN8shz9PpRGQr"
      }
    ],
    "name": "MovieLabs Studio",
    "description": "Headquarters of MovieLabs Studio",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/LymvJ1GP6RbuhtgjlJY7j"
        }
      ],
      "address": {
        "street": "222 Kearny St, Ste 300",
        "locality": "San Francisco",
        "region": "California",
        "postalCode": "CA 94108",
        "country": "US"
      },
      "coordinates": {
        "latitude": 37.79018,
        "longitude": -122.40367
      }
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/ez1rAHkRw7ebLPNnXY1Q_"
      }
    ],
    "name": "Lightstorm",
    "description": "Virtual Production Stage",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/Qz7LGOejU7-NybYTJDofq"
        }
      ],
      "address": {
        "street": "1600 Rosecrans Avenue",
        "locality": "Manhattan Beach",
        "region": "California",
        "postalCode": "CA 90266",
        "country": "US"
      },
      "coordinates": {
        "latitude": 36.12361,
        "longitude": 119.0496
      }
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/Ac3o-dmyEs8AglFKDLoT5"
      }
    ],
    "name": "Labkoat.media",
    "description": "Headquarters of Labkoat.media",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/DVzzIcqf35RQQtkvwNueQ"
        }
      ],
      "address": {
        "street": "29 Tallwood Dr.",
        "locality": "Porterville",
        "region": "California",
        "postalCode": "CA 93257",
        "country": "US"
      },
      "coordinates": {
        "latitude": 36.123611,
        "longitude": -119.049599
      }
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/VbTKuVcICZLzvr2ShHj8c"
      }
    ],
    "name": "FX-DMZ",
    "description": "Headquarters of FX-DMZ",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/vwVy1ZHlo8b-GdDE3pC76"
        }
      ],
      "address": {
        "street": "2231 Quesnel",
        "locality": "Montreal",
        "region": "Quebec",
        "postalCode": "H3J1G3",
        "country": "CA"
      },
      "coordinates": {
        "latitude": 45.48736,
        "longitude": -73.57545
      }
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/MuCFCfVeCv0mXeXdnpYSi"
      }
    ],
    "name": "coastline ",
    "description": "environment for coastline",
    "Location": null
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/TK4E45u-dwswyB7yCGgnX"
      }
    ],
    "name": "space ",
    "description": "environment for space and atmoshpere",
    "Location": null
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/tJXXp9Pbza0q6roZNHp2b"
      }
    ],
    "name": "jungle ",
    "description": "environment for jungle",
    "Location": null
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/ScUo2IEIMqiAJDSxvSP7Y"
      }
    ],
    "name": "Killamari City",
    "description": "Environment for Killmari city",
    "Location": null
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/d1_XXxQ9T3lXXWEdKwG6x"
      }
    ],
    "name": "beach ",
    "description": "environment for ocean and beach",
    "Location": null
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/RVmDAT-qUwjudelEx3rkF"
      }
    ],
    "name": "plateau",
    "description": "Environment for plateau",
    "Location": null
  }
]
