=== MovieLabs/OMC/JSON-Schema/mmc/Utility/Location.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Location",
  "description": "A particular place or position either in either the real world or the narrative world.",
  "required": [
    "identifier",
    "entityType"
  ],
  "properties": {
    "entityType": {
      "type": "string",
      "title": "Entity Type",
      "const": "Location"
    },
    "schemaVersion": {
      "$ref": "../Model/definitions.json#/properties/schemaVersion"
    },
    "instance": {
      "$ref": "../Model/definitions.json#/properties/instance"
    },
    "identifier": {
      "$ref": "../Utility/identifier.json#/properties/identifier"
    },
    "name": {
      "type": [
        "string",
        "null"
      ],
      "title": "Name"
    },
    "description": {
      "type": [
        "string",
        "null"
      ],
      "title": "Description"
    },
    "address": {
      "$ref": "#/$defs/address"
    },
    "coordinates": {
      "$ref": "#/$defs/coordinates"
    }
  },
  "additionalProperties": false,
  "$defs": {
    "address": {
      "type": [
        "object",
        "null"
      ],
      "title": "Address",
      "properties": {
        "street": {
          "type": [
            "string",
            "null"
          ],
          "title": "Street Address",
          "description": "The street address",
          "examples": [
            "1600 Ampitheatre Parkway", "221b Baker Street"
          ]
        },
        "locality": {
          "type": [
            "string",
            "null"
          ],
          "title": "Address locality",
          "description": "The locality in which the street address is, and which is in the region.",
          "examples": [
            "Mountain View", "London"
          ]
        },
        "region": {
          "type": [
            "string",
            "null"
          ],
          "title": "Address region",
          "description": "The region in which the locality is, and which is in the country",
          "examples": [
            "California", "London"
          ]
        },
        "postalCode": {
          "type": [
            "string",
            "null"
          ],
          "title": "Zip or Postal Code",
          "description": "A zip or postal code",
          "examples": [
            "94534", "NW1 6XE"
          ]
        },
        "country": {
          "type": [
            "string",
            "null"
          ],
          "title": "Country",
          "description": "The country, as an ISO 3166-1 alpha-2 country code",
          "examples": [
            "US"
          ]
        },
        "additionalProperties": true
      }
    },
    "coordinates": {
      "type": [
        "object",
        "null"
      ],
      "title": "GPS coordinates",
      "description": "A global positioning coordinate in compliance with WGS 84",
      "properties": {
        "latitude": {
          "type": [
            "number",
            "null"
          ],
          "minimum": -90,
          "maximum": 90,
          "examples": [
            37.422
          ]
        },
        "longitude": {
          "type": [
            "number",
            "null"
          ],
          "minimum": -180,
          "maximum": 180,
          "examples": [
            -122.085
          ]
        },
        "elevation": {
          "type": [
            "string",
            "null"
          ],
          "$ref": "./unitOfMeasurement.json#/properties/linearDistance",
          "examples": [
            "100m",
            "3200ft"
          ]
        }
      }
    }
  }
}

=== MovieLabs/OMC/OMC-JSON/Examples/singleEntities/Location.json
[
  {
    "schemaVersion": "https://movielabs.com/omc/json/schema/v2.6",
    "entityType": "Location",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/CJXwmiWy3cXV802h-5fWI"
      }
    ],
    "address": {
      "street": "405 Av. Ogilvy B",
      "locality": "Montr√©al",
      "region": "Quebec",
      "postalCode": "QC H3N 1M3",
      "country": "CA"
    },
    "coordinates": {
      "latitude": 45.53072,
      "longitude": -73.62522
    }
  },
  {
    "schemaVersion": "https://movielabs.com/omc/json/schema/v2.6",
    "entityType": "Location",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/CJXwmiWy3cXV802h-5fWI"
      }
    ],
    "address": {
      "street": null,
      "locality": null,
      "region": null,
      "postalCode": null,
      "country": null
    },
    "coordinates": {
      "latitude": null,
      "longitude": null
    }
  },
  {
    "schemaVersion": "https://movielabs.com/omc/json/schema/v2.6",
    "entityType": "Location",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/CJXwmiWy3cXV802h-5fWI"
      }
    ],
    "address": null,
    "coordinates": null
  }
]
