=== MovieLabs/OMC/JSON-Schema/mmc/MediaCreationContext/Character.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Character",
  "description": "A sentient entity (usually a person but not always) in the script whose specific identity is consequential to the narrative. A Character is generally identified by a specific name.",
  "required": [
    "identifier",
    "entityType"
  ],
  "properties": {
    "entityType": {
      "type": "string",
      "title": "Entity Type",
      "const": "Character"
    },
    "identifier": {
      "title": "identifier",
      "$ref": "../Utility/identifier.json"
    },
    "characterName": {
      "title": "Character Name",
      "$ref": "../Utility/completeName.json"
    },
    "description": {
      "type": "string",
      "title": "Character Description",
      "description": "A brief description of the character"
    },
    "profile": {
      "type": "object",
      "title": "Profile",
      "properties": {
        "physicalCharacteristics": {
          "type": "object",
          "title": "Physical Characteristics",
          "description": "Allows for the the description of certain physical characteristics on a character, things that might be useful to an art department, wardrobe or casting for example.",
          "properties": {
            "species": {
              "type": "string",
              "title": "Species",
              "description": "A species to which this character belongs",
              "examples": [
                "Human",
                "Borg",
                "Goblin",
                "Frog"
              ]
            },
            "hairColor": {
              "type": "string",
              "title": "Hair Color",
              "description": "The hair color of the character",
              "examples": [
                "Brown",
                "Pink",
                "Blonde",
                ""
              ]
            },
            "hairLength": {
              "type": "string",
              "title": "Hair Length",
              "description": "The length of hair of the character"
            },
            "eyeColor": {
              "type": "string",
              "title": "Eye Color",
              "description": "The color of the characters eyes"
            },
            "height": {
              "title": "height",
              "$ref": "../Utility/unitOfMeasurement.json#/properties/linearDistance"
            },
            "weight": {
              "title": "weight",
              "$ref": "../Utility/unitOfMeasurement.json#/properties/weight"
            }
          },
          "additionalProperties": false
        },
        "gender": {
          "$ref": "../Utility/gender.json"
        },
        "background": {
          "type": "object",
          "title": "background",
          "additionalProperties": true
        }
      },
      "additionalProperties": false
    },
    "Context": {
      "type": "object",
      "title": "Context",
      "properties": {
        "entityType": {
          "type": "string",
          "title": "Entity Type",
          "const": "Context"
        },
        "identifier": {
          "title": "identifier",
          "$ref": "../Utility/identifier.json"
        },
        "hasRelatedAsset": {
          "type": "object",
          "title": "hasRelatedAsset",
          "properties": {
            "Asset": {
              "type": "array",
              "items": {
                "$ref": "../Asset/Asset.json"
              }
            }
          }
        },
        "uses": {
          "type": "object",
          "title": "uses",
          "properties": {
            "NarrativeProp": {
              "type": "array",
              "items": {
                "$ref": "../MediaCreationContext/NarrativeProp.json"
              }
            }
          }
        },
        "usesWardrobe": {
          "type": "object",
          "title": "usesWardrobe",
          "properties": {
            "NarrativeWardrobe": {
              "type": "array",
              "items": {
                "$ref": "../MediaCreationContext/NarrativeWardrobe.json"
              }
            }
          }
        },
        "appearsIn": {
          "type": "object",
          "title": "appearsIn",
          "properties": {
            "NarrativeScene": {
              "type": "array",
              "items": {
                "$ref": "../MediaCreationContext/NarrativeScene.json"
              }
            }
          },
          "additionalItems": true
        },
        "isPortrayedBy": {
          "type": "object",
          "title": "isPortrayedBy",
          "properties": {
            "Participant": {
              "type": "array",
              "items": {
                "$ref": "../Participant/Participant.json"
              }
            }
          }
        },
        "hasCostume": {
          "type": "object",
          "title": "hasCostume",
          "properties": {
            "Costume": {
              "type": "array",
              "items": {
                "$ref": "../MediaCreationContext/Costume.json"
              }
            }
          },
          "additionalItems": true
        }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": false
}

=== MovieLabs/OMC/Examples/Character-dereferenced.json
{
  "entityType": "Character",
  "identifier": [
    {
      "identifierScope": "labkoat",
      "identifierValue": "chr/HNvHjXqJY9wv1IwjG-Hf1"
    }
  ],
  "characterName": {
    "scriptName": "Sven"
  },
  "description": "Sven is an unassuming Satellite repair man. He spends his time alone in his ship traveling to remote planets on the outskirt of the galaxy maintaining a network of exploration satellites. He is more of a lover than a fighter.",
  "profile": {
    "physicalCharacteristics": {
      "species": "Human",
      "hairColor": "Brown",
      "hairLength": "Short",
      "eyeColor": "Green",
      "height": "1m90cm",
      "weight": "80kg"
    },
    "background": {
      "likes": "Kiera, Space, Nature",
      "dislikes": "War, Big space cities, Conflict",
      "habits": "Sven is a bit of a sloth, happy to be far from prying eyes as he does his work at his pace. He is also a bit of a coward and has avoided the space navy at all cost. He is kind and patient and caring for the people in his life like Kiera.",
      "traits": "Sven is a helpful unassuming character who likes to be alone. He connects with his handlers like Kiera but is happy to be engrossed in his work. He is generally scared of all things and not a hero."
    }
  },
  "Context": {
    "entityType": "Context",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "cxt/377RXIREHUj5MPzsl-Sba"
      }
    ],
    "appearsIn": {
      "NarrativeScene": [
        {
          "entityType": "NarrativeScene",
          "identifier": [
            {
              "identifierScope": "labkoat",
              "identifierValue": "wrd/wz_MHOLYI3VwYx_0AX47Y"
            }
          ],
          "sceneName": {
            "fullName": "EXT - Jungle",
            "altName": "JGL"
          },
          "sceneNumber": "1",
          "description": "Title sequence with Sven bursting out of the jungle to the title sequence.",
          "slugline": [
            {
              "title": "INT/EXT",
              "text": "EXT"
            },
            {
              "title": "time",
              "text": "DAY"
            }
          ]
        },
        {
          "entityType": "NarrativeScene",
          "identifier": [
            {
              "identifierScope": "labkoat",
              "identifierValue": "wrd/St_Hh-LxAQo4ICUAtbZ0v"
            }
          ],
          "sceneName": {
            "fullName": "EXT- Space",
            "altName": "SPC"
          },
          "sceneNumber": "2",
          "description": "Sven repairs satellite and is ambushed by Trilobot",
          "slugline": [
            {
              "title": "INT/EXT",
              "text": "EXT"
            },
            {
              "title": "time",
              "text": "NIGHT"
            }
          ]
        },
        {
          "entityType": "NarrativeScene",
          "identifier": [
            {
              "identifierScope": "labkoat",
              "identifierValue": "wrd/xJpXtpM0G2QQM92TITfTf"
            }
          ],
          "sceneName": {
            "fullName": "EXT -Space Moments Later",
            "altName": "SPC"
          },
          "sceneNumber": "3",
          "description": "Sven reaches spaceship and climbs in.",
          "slugline": [
            {
              "title": "INT/EXT",
              "text": "EXT"
            },
            {
              "title": "time",
              "text": "NIGHT"
            }
          ]
        },
        {
          "entityType": "NarrativeScene",
          "identifier": [
            {
              "identifierScope": "labkoat",
              "identifierValue": "wrd/3EF7fR-xOJ7IamLr2iYsg"
            }
          ],
          "sceneName": {
            "fullName": "EXT - Atmosphere - DAY",
            "altName": "ATMO"
          },
          "sceneNumber": "4",
          "description": "Sven crashes into atmosphere and water",
          "slugline": [
            {
              "title": "INT/EXT",
              "text": "EXT"
            },
            {
              "title": "time",
              "text": "DAY"
            }
          ]
        },
        {
          "entityType": "NarrativeScene",
          "identifier": [
            {
              "identifierScope": "labkoat",
              "identifierValue": "wrd/lmPkGo1nXjJgfeNnoxArq"
            }
          ],
          "sceneName": {
            "fullName": "EXT - Beach - DAY",
            "altName": "BECH"
          },
          "sceneNumber": "5",
          "description": "Sven swims to surface and walks into beach.",
          "slugline": [
            {
              "title": "INT/EXT",
              "text": "EXT"
            },
            {
              "title": "time",
              "text": "DAY"
            }
          ]
        },
        {
          "entityType": "NarrativeScene",
          "identifier": [
            {
              "identifierScope": "labkoat",
              "identifierValue": "wrd/zH9BzX8cjf-wY6N-HE6fg"
            }
          ],
          "sceneName": {
            "fullName": "EXT- Jungle - Day",
            "altName": "JGL"
          },
          "sceneNumber": "6",
          "description": "Sven retreats to the jungle and destroys the Trilobot using exploding fruit native to the planet.",
          "slugline": [
            {
              "title": "INT/EXT",
              "text": "EXT"
            },
            {
              "title": "time",
              "text": "DAY"
            }
          ]
        },
        {
          "entityType": "NarrativeScene",
          "identifier": [
            {
              "identifierScope": "labkoat",
              "identifierValue": "wrd/1icPnKZ4LRliFd3WI9urA"
            }
          ],
          "sceneName": {
            "fullName": "EXT - Plateau - Day",
            "altName": "PLAT"
          },
          "sceneNumber": "7",
          "description": "Sven discovers city",
          "slugline": [
            {
              "title": "INT/EXT",
              "text": "EXT"
            },
            {
              "title": "time",
              "text": "DAY"
            }
          ]
        }
      ]
    },
    "usesProp": null,
    "usesWardrobe": {
      "NarrativeWardrobe": [
        {
          "entityType": "NarrativeWardrobe",
          "identifier": [
            {
              "identifierScope": "labkoat",
              "identifierValue": "wrd/Ia7-FdhY1yBFyqG_2nYW8"
            }
          ],
          "name": "Spacesuit",
          "description": "RD-12 Envrionmental Protection Suit"
        }
      ]
    }
  }
}
