=== MovieLabs/OMC/JSON-Schema/mmc/MediaCreationContext/NarrativeLocation.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "NarrativeLocation",
	"description": "A location specified or implied by the narrative.",
	"type": "object",
	"required": [
		"entityType",
		"identifier"
	],
	"properties": {
		"schemaVersion": {
			"$ref": "../Model/definitions.json#/properties/schemaVersion"
		},
		"entityType": {
			"type": "string",
			"title": "Entity Type",
			"const": "NarrativeLocation"
		},
		"instance": {
			"$ref": "../Model/instance.json"
		},
		"identifier": {
			"$ref": "../Utility/identifier.json"
		},
		"name": {
			"title": "Narrative Location Name",
			"description": "A human readable name for the location",
			"type": [
				"string",
				"null"
			]
		},
		"description": {
			"title": "Narrative Location Description",
			"description": "A brief description of the narrative location",
			"type": [
				"string",
				"null"
			]
		},
		"Location": {
			"$ref": "../Utility/Location.json"
		},
		"Context": {
			"title": "Narrative Location Context",
			"description": "Informs scope within the construction process of a Creative Work by describing related entities",
			"type": "object",
			"required": [
				"entityType",
				"identifier"
			],
			"properties": {
				"schemaVersion": {
					"$ref": "../Model/definitions.json#/properties/schemaVersion"
				},
				"entityType": {
					"type": "string",
					"title": "Entity Type",
					"const": "Context"
				},
				"instance": {
					"$ref": "../Model/instance.json"
				},
				"identifier": {
					"$ref": "../Utility/identifier.json"
				}
			},
			"additionalProperties": true
		}
	},
	"additionalProperties": true
}

=== MovieLabs/OMC/Examples/locations.json
[
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/ujQpZcShX7y6Do114nXNp"
      }
    ],
    "name": "Space",
    "description": "The vast infintite nothingness",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/OB6MeonzccsbCw4EHv3kw"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/cnFSmIYdk0j5NhYkkcjnp"
      }
    ],
    "name": "Headquarters",
    "description": "The galactic federation home base of operations",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/34T8RjoQbKCl5lnyalkmr"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/z_GgQuQK8JOzOygofIAwU"
      }
    ],
    "name": "Atmosphere",
    "description": "The upper atmoshere of SR-232",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/gOeG3sVZgo2PGogMQOZqx"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/L5VqKriC9OFF2DsaLc66u"
      }
    ],
    "name": "Planet",
    "description": "Planet SR-232",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/W6k3INeUC8pVIJHoeZpw7"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/ym4RXT4JbXxIAAc1uTUXX"
      }
    ],
    "name": "Ocean",
    "description": "Quadrant 4 of Planet SR-232",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/6k8-CFXqXdyuztG19jDk0"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/4h-qk9I4CW6nVIbHjpBEr"
      }
    ],
    "name": "Coastline",
    "description": "Rocky outcrops of Quadrant 4 of Planet SR-232",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/YJVoLzantYRbkJneXXuVA"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/50DwTikSnhJViFrABXvGF"
      }
    ],
    "name": "Beach",
    "description": "Sandy beach leading into jungle on coastline",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/6mZcMvDTYRQnfwQOH2GcA"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/JR_953OF4aawPxxjrhQgS"
      }
    ],
    "name": "Jungle",
    "description": "Deep thick brush, trees and fruits on rocky terrain",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/vVhJcyJnne9h-gkjkJNuZ"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/ryfjgiLuoYBZePKoW9Yxy"
      }
    ],
    "name": "Plateau",
    "description": "Volcanic ridge above valley",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/eEgBqiGajyZCr2mb5mPpo"
        }
      ]
    }
  },
  {
    "entityType": "NarrativeLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/EZ4G2BwwADdGAYwsJZprm"
      }
    ],
    "name": "Killamari City",
    "description": "Hidden mining and headquarters of Killamari on Planet SR-232",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/PNI-deSI_YJulZ99V6zMP"
        }
      ]
    }
  },
  {
    "entityType": "ShootingLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/DBMKDFZ5G7PBwtgK2PXBG"
      }
    ],
    "name": "Game On ",
    "description": "Motion Capture Stage",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/CJXwmiWy3cXV802h-5fWI"
        }
      ]
    },
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/74J6YVjYu7jTmhuoKCVx9"
        }
      ]
    }
  },
  {
    "entityType": "ShootingLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/ez1rAHkRw7ebLPNnXY1Q_"
      }
    ],
    "name": "Lightstorm",
    "description": "Virtual Production Stage",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/Qz7LGOejU7-NybYTJDofq"
        }
      ]
    },
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/LXmTA23HTrvs4o-XyYnAm"
        }
      ]
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/Ac3o-dmyEs8AglFKDLoT5"
      }
    ],
    "name": "Labkoat.media",
    "description": "Headquarters of Labkoat.media",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/DVzzIcqf35RQQtkvwNueQ"
        }
      ]
    },
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/0ePi-n5yunaJfgLvicU7K"
        }
      ]
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/06CvKXkLgN8shz9PpRGQr"
      }
    ],
    "name": "MovieLabs Studio",
    "description": "Headquarters of MovieLabs Studio",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/LymvJ1GP6RbuhtgjlJY7j"
        }
      ]
    },
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/MJsu5EHqZ_Zql09enQ8aE"
        }
      ]
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/VbTKuVcICZLzvr2ShHj8c"
      }
    ],
    "name": "FX-DMZ",
    "description": "Headquarters of FX-DMZ",
    "Location": {
      "entityType": "Location",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "loc/vwVy1ZHlo8b-GdDE3pC76"
        }
      ]
    },
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/Qu0MpN4umGn70YXud-Myj"
        }
      ]
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/4ZwI6mZZlTTbNdkkNKnWP"
      }
    ],
    "name": "Participant locations",
    "description": "Various person locations",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/gcKMAYeldjR_pOhhmYmeQ"
        }
      ]
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/TK4E45u-dwswyB7yCGgnX"
      }
    ],
    "name": "space ",
    "description": "environment for space and atmoshpere",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/qySUvAwbpSKPK3OdAubiG"
        }
      ]
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/d1_XXxQ9T3lXXWEdKwG6x"
      }
    ],
    "name": "beach ",
    "description": "environment for ocean and beach",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/HdtYp9aQgH2Odfg6QvsDt"
        }
      ]
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
        "identifierValue": "loc/MuCFCfVeCv0mXeXdnpYSi"
      }
    ],
    "name": "coastline ",
    "description": "environment for coastline",
    "Context": {
      "entityType": "Context",
      "identifier": [
        {
          "identifierScope": "labkoat",
          "identifierValue": "cxt/0NkWtf0TjVk82CRduelbv"
        }
      ]
    }
  },
  {
    "entityType": "ProductionLocation",
    "identifier": [
      {
        "identifierScope": "labkoat",
